name: Windows build

on:
  push:
    branches: [ develop ]

jobs:
  win-build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Enable MSVC commands
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        shell: bash
        run: ./scripts/win-install-qt.sh

      - name: Install MPV
        shell: cmd
        run: scripts\win-install-mpv.bat

      - name: Build
        run: |-
          cmake -A x64 -DCMAKE_PREFIX_PATH=C:/Qt/6.1.2/msvc2019_64 -DUSE_QT6=ON .
          cmake --build . --config Release

  linux-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dpkg tools
        run: |-
          sudo apt-get update
          sudo apt-get install -y cdbs devscripts equivs fakeroot

      - name: Install dependencies
        run: sudo mk-build-deps -ir -t "apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends"

      - name: Build packages
        run: dpkg-buildpackage -b -uc -us