name: Linux build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-16.04

    env:
      QT_BASE_DIR: /opt/qt515
      PATH: /opt/qt515/bin/:$PATH
      UPLOADTOOL_ISPRERELEASE: true

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |-
          sudo add-apt-repository -y ppa:cos-lyk/libmpv-xenial
          sudo add-apt-repository -y ppa:cos-lyk/qt-lite
          sudo apt-get update
          sudo apt-get install -y desktop-file-utils \
                                  ffmpeg \
                                  libcurl4-openssl-dev \
                                  libgl1-mesa-dev \
                                  libglu1-mesa-dev \
                                  libmpv-dev \
                                  qt515base \
                                  qt515declarative \
                                  qt515quickcontrols2 \
                                  qt515tools

      - name: Build
        run: |-
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$QT_BASE_DIR -DCMAKE_INSTALL_PREFIX=/usr .
          make