name: Windows build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        version: 5.15.2

      - name: Install MPV
        run: |-
          curl -Lo libmpv.7z https://deac-riga.dl.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-x86_64-20210214-git-93066ff.7z
          7z x -olibmpv libmpv.7z
          cd libmpv
          mv include mpv
          lib /def:mpv.def /name:mpv-1.dll /out:mpv.lib /MACHINE:X64
          cd ..

      - name: Build
        run: |-
          cmake -A x64 .
          cmake --build . --config Release