name: Windows build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        run: ./scripts/win-install-qt.sh

      - name: Install MPV
        run: ./scripts/win-install-mpv.sh

      - name: Build
        run: |-
          cmake -A x64 .
          cmake --build . --config Release